---
#rpm -Uvh http://mirror.webtatic.com/yum/el6/latest.rpm
#yum remove php-common       # Need to remove this, otherwise it conflicts
#yum install php56w
#yum install php56w-mysql
#yum install php56w-common
#yum install php56w-pdo
#yum install php56w-opcache

- name: Installing php repo
  command: rpm -Uvh http://mirror.webtatic.com/yum/el6/latest.rpm

- name: Installing zabbix server dependencies ...
  yum: name={{ item }} state=installed
  with_items:
      - httpd
      - httpd-devel
      - mysql
      - mysql-server
      - php56w
      - php56w-mysql
      - php56w-devel
      - php56w-cli
      - php56w-common
      - php56w-pear
      - php56w-gd
      - php56w-mysql
      - php56w-mbstring 
      - php56w-bcmath
      - php56w-xml
      - MySQL-python

- service: name=httpd state=started
- service: name=mysqld state=started

- include: mysql_secure_installation.yml

- name: Installing zabbix server ...
  command: rpm -Uvh http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm warn=no

- yum: name={{ item }}  state=present
  with_items:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-agent 
#      - zabbix-java-gateway

- name: Configuring php setting ...
  template: src=zabbix.conf.j2 dest=/etc/httpd/conf.d/zabbix.conf owner=root group=root mode=0644

- name: Mysql Configuration
  command: 'mysql -u root -p{{ mysql_root_password }} -e "{{ item }}"'
  with_items:
    - CREATE DATABASE zabbixdb CHARACTER SET UTF8;
    - GRANT ALL PRIVILEGES on zabbixdb.* to zabbix@localhost IDENTIFIED BY 'password';
    - FLUSH PRIVILEGES;
  

- name: Importing database ...
  shell: "zcat /usr/share/doc/zabbix-server-mysql-3*/create.sql.gz | mysql -uroot zabbixdb  -p{{ mysql_root_password }}"

- name: Adding zabbix configuration file ...
  template: src=zabbix-server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=root group=zabbix mode=0640

- name: Configuring zabbix ui part ...
  template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php owner=apache group=apache mode=0644

- service: name=zabbix-server state=started

- include: zabbix_agent.yml 

